/**
 * @fileoverview Markdown Exporter for FlareInspect
 * @description Exports findings in Markdown format for git-friendly reporting
 * @module exporters/markdown
 */

const dayjs = require('dayjs');
const logger = require('../core/utils/logger');

class MarkdownExporter {
  async export(assessment) {
    logger.info('Exporting assessment to Markdown format');

    const lines = [];
    const score = assessment.score || {};
    const summary = assessment.summary || {};
    const findings = assessment.findings || [];

    lines.push(`# FlareInspect Security Assessment Report`);
    lines.push('');
    lines.push(`**Assessment ID**: ${assessment.assessmentId}`);
    lines.push(`**Account**: ${assessment.account?.name || 'Unknown'}`);
    lines.push(`**Date**: ${dayjs(assessment.startedAt).format('YYYY-MM-DD HH:mm')}`);
    lines.push(`**Duration**: ${assessment.executionTime || 0}ms`);
    lines.push('');

    // Executive Summary
    lines.push('## Executive Summary');
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|--------|-------|');
    lines.push(`| **Security Score** | ${score.overallScore || 0}/100 |`);
    lines.push(`| **Grade** | ${score.grade || 'F'} |`);
    lines.push(`| **Total Checks** | ${summary.totalChecks || 0} |`);
    lines.push(`| **Passed** | ${summary.passedChecks || 0} |`);
    lines.push(`| **Failed** | ${summary.failedChecks || 0} |`);
    lines.push(`| **Critical** | ${summary.criticalFindings || 0} |`);
    lines.push(`| **High** | ${summary.highFindings || 0} |`);
    lines.push(`| **Medium** | ${summary.mediumFindings || 0} |`);
    lines.push(`| **Low** | ${summary.lowFindings || 0} |`);
    lines.push('');

    // Findings by severity
    const severityOrder = ['critical', 'high', 'medium', 'low', 'informational'];
    severityOrder.forEach(severity => {
      const severityFindings = findings.filter(f => f.severity === severity && f.status === 'FAIL');
      if (severityFindings.length === 0) return;

      lines.push(`## ${severity.charAt(0).toUpperCase() + severity.slice(1)} Findings`);
      lines.push('');

      severityFindings.forEach(f => {
        lines.push(`### ${f.checkTitle}`);
        lines.push('');
        lines.push('| Field | Value |');
        lines.push('|-------|-------|');
        lines.push(`| Check ID | ${f.checkId} |`);
        lines.push(`| Service | ${f.service} |`);
        lines.push(`| Status | ${f.status} |`);
        lines.push(`| Resource | ${f.resourceId || 'N/A'} |`);
        lines.push(`| Description | ${f.description} |`);
        lines.push(`| Remediation | ${f.remediation} |`);
        lines.push('');
      });
    });

    // Service breakdown
    const byService = summary.byService || {};
    if (Object.keys(byService).length > 0) {
      lines.push('## Findings by Service');
      lines.push('');
      lines.push('| Service | Issues |');
      lines.push('|---------|--------|');
      Object.entries(byService)
        .filter(([_, count]) => count > 0)
        .sort((a, b) => b[1] - a[1])
        .forEach(([service, count]) => {
          lines.push(`| ${service} | ${count} |`);
        });
      lines.push('');
    }

    // Recommendations
    lines.push('## Recommendations');
    lines.push('');
    const report = assessment.report || {};
    const recs = report.recommendations || {};
    if (recs.immediate?.length > 0) {
      lines.push('### Immediate Actions (0-24 hours)');
      recs.immediate.forEach(r => lines.push(`- ${r.title}: ${r.action}`));
      lines.push('');
    }
    if (recs.shortTerm?.length > 0) {
      lines.push('### Short-term (1-30 days)');
      recs.shortTerm.forEach(r => lines.push(`- ${r.title}: ${r.action}`));
      lines.push('');
    }

    lines.push('---');
    lines.push(`*Generated by FlareInspect v1.0.0 | IONSEC.IO*`);

    return lines.join('\n');
  }
}

module.exports = MarkdownExporter;
